modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
	modId="skilltree"
	version="0.5.6"
	displayName="Passive Skill Tree"
	authors="Daripher"
	description='''Adds passive skill tree with player class system'''
	credits='''Thanks to: LittleOdie for some ideas. Prince_Vladislav for some of the icons. All the modpack makers who use my mod. All the people on my discord server.'''
	
[[dependencies.skilltree]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.skilltree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.skilltree]]
    modId="attributefix"
    mandatory=true
    versionRange="[17.2.6,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.skilltree]]
    modId="maxhealthfix"
    mandatory=true
    versionRange="[8.0.1,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.skilltree]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.4.1,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.skilltree]]
    modId="apotheosis"
    mandatory=false
    versionRange="[6.3.3,)"
    ordering="NONE"
    side="BOTH"
